# Generated by Django 5.2.3 on 2025-07-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_downloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineeConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('examinee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.examineeaccount')),
            ],
        ),
    ]
