# Generated by Django 5.2.3 on 2025-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_examineeconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineeaccount',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
