# Generated by Django 5.2.3 on 2025-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_examineeaccount_birthdate_examineeaccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examineeaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='country',
            field=models.CharField(default='Philippines', max_length=50),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='highest_education_level',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate', 'Doctorate')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='level',
            field=models.CharField(blank=True, choices=[('Rank and File', 'Rank and File'), ('Supervisory', 'Supervisory'), ('Managerial', 'Managerial')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examineeaccount',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examineeaccount',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examineeaccount',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examineeaccount',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examineeaccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examineeaccount',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examineeaccount',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examineeaccount',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
