# Generated by Django 5.2.3 on 2025-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_examineeaccount_city_examineeaccount_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examineeaccount',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
