# Generated by Django 5.2.3 on 2025-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_examineeaccount_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examineeaccount',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
