# Generated by Django 5.2.3 on 2025-08-10 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_examineeaccount_birthdate'),
        ('exams', '0016_alter_exam_options_exam_sort_order'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.FloatField(blank=True, null=True)),
                ('scaled_score', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='accounts.examineeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('qtype', models.CharField(choices=[('mcqquestion', 'MCQ'), ('likertquestion', 'Likert'), ('truefalsequestion', 'True/False'), ('essayquestion', 'Essay')], max_length=32)),
                ('mcq_choice_id', models.IntegerField(blank=True, null=True)),
                ('likert_value', models.IntegerField(blank=True, null=True)),
                ('truefalse_value', models.BooleanField(blank=True, null=True)),
                ('essay_text', models.TextField(blank=True, null=True)),
                ('raw_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.exam')),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.examineeaccount')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='responses.examattempt')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamineeProfile',
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['examinee', 'exam'], name='responses_e_examine_ed251a_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='responses_e_exam_id_263bae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together={('examinee', 'exam', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question_id'], name='responses_a_attempt_c6c0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['examinee', 'exam'], name='responses_a_examine_05f911_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['qtype'], name='responses_a_qtype_1719f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question_id')},
        ),
    ]
