# Generated by Django 5.2.3 on 2025-08-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_examineeaccount_birthdate'),
        ('exams', '0016_alter_exam_options_exam_sort_order'),
        ('responses', '0002_examattempt_answer_delete_examineeprofile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'qtype', 'question_id')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'qtype', 'question_id'], name='responses_a_attempt_d1cba1_idx'),
        ),
    ]
