# Generated by Django 5.2.3 on 2025-06-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_likertscale_likertoption_mcqchoice_delete_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqchoice',
            old_name='text',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='mcqchoice',
            name='question_id',
        ),
        migrations.AddField(
            model_name='mcqchoice',
            name='question_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
