# Generated by Django 5.2.3 on 2025-06-30 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_text_mcqchoice_choice_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestion',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='mcqchoice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.mcqquestion'),
        ),
    ]
