# Generated by Django 5.2.3 on 2025-06-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_text_mcqquestion_question_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='EssayQuestion',
        ),
        migrations.AlterModelOptions(
            name='essayquestion',
            options={'verbose_name': 'Essay Question', 'verbose_name_plural': 'Essay Questions'},
        ),
        migrations.AlterModelOptions(
            name='testbattery',
            options={'verbose_name': 'Test Battery', 'verbose_name_plural': 'Test Batteries'},
        ),
    ]
