# Generated by Django 5.2.3 on 2025-06-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_question_essayquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Optional explanation for evaluators or students.'),
        ),
    ]
