# Generated by Django 5.2.3 on 2025-07-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_truefalsequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='is_true',
        ),
        migrations.CreateModel(
            name='TFChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.truefalsequestion')),
            ],
        ),
    ]
