# Generated by Django 5.2.3 on 2025-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_truefalsequestion_is_true_tfchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='truefalsequestion',
            name='correct_answer',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=True),
        ),
        migrations.DeleteModel(
            name='TFChoice',
        ),
    ]
