# Generated by Django 5.2.3 on 2025-07-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_remove_truefalsequestion_correct_answer_tfchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikertQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.likertscale')),
            ],
        ),
        migrations.DeleteModel(
            name='LikertOption',
        ),
    ]
