# Generated by Django 5.2.3 on 2025-07-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_likertquestion_delete_likertoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikertOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.likertscale')),
            ],
        ),
    ]
