# Generated by Django 5.2.3 on 2025-07-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_likertoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('expiration_from', models.DateField()),
                ('expiration_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.testbattery')),
            ],
        ),
    ]
