# Generated by Django 5.2.3 on 2025-07-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_examineeaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayquestion',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='type',
        ),
        migrations.DeleteModel(
            name='ExamineeAccount',
        ),
    ]
