# Generated by Django 5.2.3 on 2025-07-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_remove_essayquestion_question_type_remove_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqchoice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.mcqquestion'),
        ),
    ]
