# Generated by Django 5.2.3 on 2025-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_alter_mcqchoice_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='exam',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
